/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';
import { LiWEResponse, sendParametersError, sendResponse } from '../../liwe/response';

import {
	// endpoints function
	delete_media_delete_items, delete_media_folder_delete, get_media_download, get_media_folder_root, get_media_folders_tree,
	get_media_get, get_media_get_latest, get_media_list, get_media_search, patch_media_folder_rename,
	patch_media_meta_update, post_media_folder_create, post_media_upload, post_media_upload_chunk_add, post_media_upload_chunk_start,
	// functions
	media_get_multi, mm_media_get,
} from './methods';

import {
	Media, MediaBase, MediaBaseKeys, MediaBind, MediaBindKeys,
	MediaFolder, MediaFolderKeys, MediaKeys, MediaTreeItem, MediaTreeItemKeys,
} from './types';

/*=== f2c_start __header ===*/
import { mediamanager_db_init } from './methods';
/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - mediamanager " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "mediamanager", l ) );
	mediamanager_db_init( liwe );

	app.post( '/api/media/upload/chunk/start', async ( req: ILRequest, res: ILResponse ) => {
		const { id_folder, filename, size, title, tags, anonymous, ___errors } = typed_dict( req.body, [
			{ name: "id_folder", type: "string", required: true },
			{ name: "filename", type: "string", required: true },
			{ name: "size", type: "number", required: true },
			{ name: "title", type: "string" },
			{ name: "tags", type: "string[]" },
			{ name: "anonymous", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await post_media_upload_chunk_start( req, id_folder, filename, size, title, tags, anonymous );
		sendResponse( res, response );
	} );

	app.post( '/api/media/upload/chunk/add', async ( req: ILRequest, res: ILResponse ) => {
		let { id_upload, start, ___errors } = typed_dict( req.query, [
			{ name: "id_upload", type: "string", required: true },
			{ name: "start", type: "number", required: true }
		] );

		if ( ___errors.length ) return send_error( res, { message: `Parameters error: ${ ___errors.join( ', ' ) }` } );

		const response = await post_media_upload_chunk_add( req, id_upload, start );
		sendResponse( res, response );
	} );

	app.post( '/api/media/folder/create', perms( [ "media.folder" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { id_parent, name, ___errors } = typed_dict( req.body, [
			{ name: "id_parent", type: "string", required: true },
			{ name: "name", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await post_media_folder_create( req, id_parent, name );
		sendResponse( res, response );
	} );

	app.patch( '/api/media/folder/rename', perms( [ "media.folder" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { id_folder, name, ___errors } = typed_dict( req.body, [
			{ name: "id_folder", type: "string", required: true },
			{ name: "name", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await patch_media_folder_rename( req, id_folder, name );
		sendResponse( res, response );
	} );

	app.delete( '/api/media/folder/delete', perms( [ "media.folder_delete" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { id_folder, ___errors } = typed_dict( req.body, [
			{ name: "id_folder", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await delete_media_folder_delete( req, id_folder );
		sendResponse( res, response );
	} );

	app.get( '/api/media/folder/root', async ( req: ILRequest, res: ILResponse ) => {


		const response = await get_media_folder_root( req, );
		sendResponse( res, response );
	} );

	app.get( '/api/media/list', perms( [ "is-logged" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { id_folders, ___errors } = typed_dict( req.query as any, [
			{ name: "id_folders", type: "string[]" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await get_media_list( req, id_folders );
		sendResponse( res, response );
	} );

	app.get( '/api/media/get', async ( req: ILRequest, res: ILResponse ) => {
		const { id, ___errors } = typed_dict( req.query as any, [
			{ name: "id", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await get_media_get( req, id );
		sendResponse( res, response );
	} );

	app.get( '/api/media/folders/tree', async ( req: ILRequest, res: ILResponse ) => {
		const { id_folder, ___errors } = typed_dict( req.query as any, [
			{ name: "id_folder", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await get_media_folders_tree( req, id_folder );
		sendResponse( res, response );
	} );

	app.delete( '/api/media/delete/items', perms( [ "media.delete" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { medias, ___errors } = typed_dict( req.body, [
			{ name: "medias", type: "string[]", required: true }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await delete_media_delete_items( req, medias );
		sendResponse( res, response );
	} );

	app.post( '/api/media/upload', perms( [ "media.create" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { title, module, id_folder, tags, ___errors } = typed_dict( req.body, [
			{ name: "title", type: "string" },
			{ name: "module", type: "string" },
			{ name: "id_folder", type: "string" },
			{ name: "tags", type: "string[]" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await post_media_upload( req, title, module, id_folder, tags );
		sendResponse( res, response );
	} );

	app.get( '/api/media/search', perms( [ "is-logged" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { title, name, type, tags, year, skip, rows, ___errors } = typed_dict( req.query as any, [
			{ name: "title", type: "string" },
			{ name: "name", type: "string" },
			{ name: "type", type: "string" },
			{ name: "tags", type: "string[]" },
			{ name: "year", type: "number" },
			{ name: "skip", type: "number" },
			{ name: "rows", type: "number" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await get_media_search( req, title, name, type, tags, year, skip, rows );
		sendResponse( res, response );
	} );

	app.get( '/api/media/get/latest', perms( [ "is-logged" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { skip, rows, ___errors } = typed_dict( req.query as any, [
			{ name: "skip", type: "number" },
			{ name: "rows", type: "number" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await get_media_get_latest( req, skip, rows );
		sendResponse( res, response );
	} );

	app.patch( '/api/media/meta/update', perms( [ "media.create" ] ), async ( req: ILRequest, res: ILResponse ) => {
		const { id, title, tags, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "title", type: "string" },
			{ name: "tags", type: "string[]" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await patch_media_meta_update( req, id, title, tags );
		sendResponse( res, response );
	} );

	app.get( '/api/media/download', async ( req: ILRequest, res: ILResponse ) => {
		const { id, ___errors } = typed_dict( req.query as any, [
			{ name: "id", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError( res, ___errors );

		const response = await get_media_download( req, id );
		sendResponse( res, response );
	} );

};
