/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"media.create": "Can create a new media",
	"media.folder": "Can create media folders",
	"media.delete": "Can delete a media",
	"media.folder_delete": "Can delete a media folder",
};

export default permissions;
